/* eslint-disable */
// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Monitorable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Monitorable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMonitorable(bb:flatbuffers.ByteBuffer, obj?:Monitorable):Monitorable {
  return (obj || new Monitorable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMonitorable(bb:flatbuffers.ByteBuffer, obj?:Monitorable):Monitorable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Monitorable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uid():string|null
uid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMonitorable(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUid(builder:flatbuffers.Builder, uidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uidOffset, 0);
}

static endMonitorable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // uid
  return offset;
}

static createMonitorable(builder:flatbuffers.Builder, uidOffset:flatbuffers.Offset):flatbuffers.Offset {
  Monitorable.startMonitorable(builder);
  Monitorable.addUid(builder, uidOffset);
  return Monitorable.endMonitorable(builder);
}
}
