/**
 * Errors codes enums.
 */
enum Errors {
  CLI_ERR_UNKNOWN_OPTION = 1,
  CLI_ERR_REQ_PATH_MISSED = 2,
  CLI_ERR_FILE_NOT_FOUND = 3,
  CLI_ERR_INVALID_HOST_VALUE = 4,
  CLI_ERR_INVALID_PORT_VALUE = 5,
  CLI_ERR_REQ_HOST_MISSED = 6,
  CLI_ERR_REQ_PORT_MISSED = 7,
}
export default Errors;
